* Abstract
If you already know everything, you can't learn anything new. The most important
lesson I've learned through my career has been to consistently check my own ego
so I can learn from those around me. Being humble helps us better connect to
others, make stronger technical decisions, and most significantly, have a better
relationship with ourselves.

That lesson surprised me because I had never thought of myself as someone with
an ego. However, egotism is deceptive and it shows up in many ways like being
stubborn, becoming defensive, or not listening. In this talk, I'll share
experiences from my development life and how ego affected the social and
technical outcomes, as well as how humility improved them. Attendees will come
away with specific strategies for recognizing when their actions are being
influenced by ego and how to temper that effect.
* Ideas
** Other people's time is more important than yours
- They have more pressing things to do
- PR reviews
- Ticket finishing and testing
** Some people are bristly
- Don't get defensive
- Marcus Aurelius quote about people being assholes
** Code does not belong to you
- Other people need to change your code
- Being too attached or territorial about it is bad for everyone
- Ownership is about responsibility, not owning things
* Books
** Ego is the enemy, Ryan Holiday
** Extreme ownership, Jocko Willink
